spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_springboot_example_dev?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 123456

mybatis:
  configuration:
    mapUnderscoreToCamelCase: true

# ????
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
#jackson:
#    default-property-inclusion: NON_NULL